In [ ]:
# 1d np array

import numpy as np

x = np.array ([i for i in range(1,21)])

print("sum =",np.sum(x))
print("mean =",np.mean(x))
print("median =",np.median(x))
print("std =",np.std(x))
print("indices =",np.where(x>10))

sum = 210
mean = 10.5
median = 10.5
std = 5.766281297335398
indices = (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)


we import numpy
then we initialise x
x is array and has 20 values
now we use np.sum,.mean,.median,.std
to calculate sum, mean, median, standard deviation
of x.
we use np.where to get the indices where x is greater than 10

In [72]:
# 2d np array
arr = np.arange(1,17).reshape(4,4)
print(f"original:\n{arr}")

tarr = arr.T
print(f"transposed:\n{tarr}")

original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
transposed:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


we initialise arr 
in this we arrange 16 numbers from 1 to 16
using np.arange(1,17).
then we reshape this array into 4x4
to make it 2d using .reshape(4,4)
we use .T to transpose this array and we store
it in tarr variable

In [ ]:
print("Original Array")
print("column wise sums =", np.sum(arr, axis=0))
print("row wise sums =", np.sum(arr, axis=1))
print("Transposed Array")
print("column wise sums =", np.sum(tarr, axis=0))
print("row wise sums =", np.sum(tarr, axis=1))

Original Array
column wise sums = [28 32 36 40]
row wise sums = [10 26 42 58]
Transposed Array
column wise sums = [10 26 42 58]
row wise sums = [28 32 36 40]


we print the column wise sum of the original array
using np.sum and we pass parameter axis=0 to make it column wise
if we pass axis=1 here it will become row wise which we print
after this, then we repeat the process for transposed array
and just replace the variable arr with tarr.

In [96]:
arr = np.array([i for i in range(2,11)])
arr2 = np.array([i for i in range(11,20)])

arr = arr.reshape(3,3)
arr2 = arr2.reshape(3,3)

print(arr)
print(arr2)

addition = arr+arr2
print("addition\n",addition)

subtraction = arr-arr2
print("subtraction\n",subtraction)

multiplication = arr*arr2
print("multiplication\n",multiplication)

print("dot product\n", np.dot(arr, arr2))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
addition
 [[13 15 17]
 [19 21 23]
 [25 27 29]]
subtraction
 [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
multiplication
 [[ 22  36  52]
 [ 70  90 112]
 [136 162 190]]
dot product
 [[132 141 150]
 [258 276 294]
 [384 411 438]]


we create 2 arrays arr,arr2
arr has numbers 2 to 10
arr2 has numbers 11 to 19
we .reshape both to 3x3

we perform operations by 
arr+arr2, arr-arr2, arr*arr2
we use np.dot and pass arr, arr2
to get the dot product

In [138]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

sliced_arr = arr[:2,-2:]
print(sliced_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]


we create arr with values 1 to 12 using np.arange(1,13)
then we reshape it to 3x4 using .reshape(3,4)

*slice is different than drop. slice is selecting while drop is removing.

we initialise sliced_arr and we store arr but with first 2 rows
sliced and last 2 columns sliced using arr[:2,-2:]
:2 is for first 2 rows and after comma -2: is for last 2 columns